__author__ = 'anna'

"""
Addition to pdb2ins.py, the pdb2ins program.
This subroutine shall create the instructions for all residues.
"""

rtabAll = {'All': ['RTAB_* Cvol CA',
                   'RTAB_* Omeg CA_+ N_+ C CA',
                   'RTAB_* Phi C_- N CA C',
                   'RTAB_* Psi N CA C N_+\n'],
           # 'Ala': [],
           'Arg': ['RTAB_ARG Chi1 N CA CB CG',
                   'RTAB_ARG Chi2 CA CB CG CD',
                   'RTAB_ARG Chi3 CB CG CD NE',
                   'RTAB_ARG Chi4 CG CD NE CZ\n'],
           'Asn': ['RTAB_ASN Chi1 N CA CB CG',
                   'RTAB_ASN Chi2 CA CB CG OD1\n'],
           'Asp': ['RTAB_ASP Chi1 N CA CB CG',
                   'RTAB_ASP Chi2 CA CB CG OD1\n'],
           'Cys': ['RTAB_CYS Chi1 N CA CB SG\n'],
           'Gln': ['RTAB_GLN Chi1 N CA CB CG',
                   'RTAB_GLN Chi2 CA CB CG CD',
                   'RTAB_GLN Chi3 CB CG CD OE1\n'],
           'Glu': ['RTAB_GLU Chi1 N CA CB CG',
                   'RTAB_GLU Chi2 CA CB CG CD',
                   'RTAB_GLU Chi3 CB CG CD OE1\n'],
           'His': ['RTAB_HIS Chi1 N CA CB CG',
                   'RTAB_HIS Chi2 CA CB CG ND1\n'],
           'Ile': ['RTAB_ILE Chi1 N CA CB CG1',
                   'RTAB_ILE Chi2 CA CB CG1 CD1',
                   'RTAB_ILE Cvol CB\n'],
           'Leu': ['RTAB_LEU Chi1 N CA CB CG',
                   'RTAB_LEU Chi2 CA CB CG CD1\n'],
           'Lys': ['RTAB_LYS Chi1 N CA CB CG',
                   'RTAB_LYS Chi2 CA CB CG CD',
                   'RTAB_LYS Chi3 CB CG CD CE',
                   'RTAB_LYS Chi4 CG CD CE NZ\n'],
           'Met': ['RTAB_MET Chi1 N CA CB CG',
                   'RTAB_MET Chi2 CA CB CG SD',
                   'RTAB_MET Chi3 CB CG SD CE\n'],
           'Phe': ['RTAB_PHE Chi1 N CA CB CG',
                   'RTAB_PHE Chi2 CA CB CG CD1\n'],
           'Pro': ['RTAB_PRO Chi1 N CA CB CG',
                   'RTAB_PRO Chi2 CA CB CG CD',
                   'RTAB_PRO Chi3 CB CG CD N\n'],
           'Ser': ['RTAB_SER Chi1 N CA CB OG\n'],
           'Thr': ['RTAB_THR Chi1 N CA CB OG1',
                   'RTAB_THR Cvol CB\n'],
           'Trp': ['RTAB_TRP Chi1 N CA CB CG',
                   'RTAB_TRP Chi2 CA CB CG CD1\n'],
           'Tyr': ['RTAB_TYR Chi1 N CA CB CG',
                   'RTAB_TYR Chi2 CA CB CG CD1\n'],
           'Val': ['RTAB_VAL Chi1 N CA CB CG1\n']}

hfixAll = {  # 'All': [],
             'Ala': ['REM HFIX_ALA 43 N',
                     'REM HFIX_ALA 13 CA',
                     'REM HFIX_ALA 33 CB\n'],
             'Arg': ['REM HFIX_ARG 13 CA',
                     'REM HFIX_ARG 23 CB CG CD',
                     'REM HFIX_ARG 43 N NE',
                     'REM HFIX_ARG 93 NH1 NH2\n'],
             'Asn': ['REM HFIX_ASN 43 N',
                     'REM HFIX_ASN 13 CA',
                     'REM HFIX_ASN 23 CB',
                     'REM HFIX_ASN 93 ND2\n'],
             'Asp': ['REM HFIX_ASP 43 N',
                     'REM HFIX_ASP 13 CA',
                     'REM HFIX_ASP 23 CB\n'],
             'Cys': ['REM HFIX_CYS 43 N',
                     'REM HFIX_CYS 13 CA',
                     'REM HFIX_CYS 23 CB\n'],
             'Gln': ['REM HFIX_GLN 43 N',
                     'REM HFIX_GLN 13 CA',
                     'REM HFIX_GLN 23 CB CG',
                     'REM HFIX_GLN 93 NE2\n'],
             'Glu': ['REM HFIX_GLU 43 N',
                     'REM HFIX_GLU 13 CA',
                     'REM HFIX_GLU 23 CB CG\n'],
             'Gly': ['REM HFIX_GLY 43 N',
                     'REM HFIX_GLY 23 CA\n'],
             'His': ['REM HFIX_HIS 13 CA',
                     'REM HFIX_HIS 23 CB',
                     'REM HFIX_HIS 43 N ND1 CE1 CD2\n'],
             'Ile': ['REM HFIX_ILE 43 N',
                     'REM HFIX_ILE 13 CA CB',
                     'REM HFIX_ILE 23 CG1',
                     'REM HFIX_ILE 33 CD1 CG2\n'],
             'Leu': ['REM HFIX_LEU 43 N',
                     'REM HFIX_LEU 13 CA CG',
                     'REM HFIX_LEU 23 CB',
                     'REM HFIX_LEU 33 CD1 CD2\n'],
             'Lys': ['REM HFIX_LYS 43 N',
                     'REM HFIX_LYS 13 CA',
                     'REM HFIX_LYS 23 CB CG CD CE',
                     'REM HFIX_LYS 33 NZ\n'],
             'Met': ['REM HFIX_MET 43 N',
                     'REM HFIX_MET 13 CA',
                     'REM HFIX_MET 23 CB CG',
                     'REM HFIX_MET 33 CE\n'],
             'Phe': ['REM HFIX_PHE 13 CA',
                     'REM HFIX_PHE 23 CB',
                     'REM HFIX_PHE 43 N CD1 CD2 CE1 CE2 CZ\n'],
             'Pro': ['REM HFIX_PRO 13 CA',
                     'REM HFIX_PRO 23 CB CG CD\n'],
             'Ser': ['REM HFIX_SER 43 N',
                     'REM HFIX_SER 13 CA',
                     'REM HFIX_SER 23 CB',
                     'REM HFIX_SER 83 OG\n'],
             'Thr': ['REM HFIX_THR 43 N',
                     'REM HFIX_THR 13 CA CB',
                     'REM HFIX_THR 33 CG2',
                     'REM HFIX_THR 83 OG1\n'],
             'Trp': ['REM HFIX_TRP 13 CA',
                     'REM HFIX_TRP 23 CB',
                     'REM HFIX_TRP 43 N CD1 NE1 CZ2 CH2 CZ3 CE3\n'],
             'Tyr': ['REM HFIX_TYR 13 CA',
                     'REM HFIX_TYR 23 CB',
                     'REM HFIX_TYR 43 N CD1 CD2 CE1 CE2',
                     'REM HFIX_TYR 83 OH\n'],
             'Val': ['REM HFIX_VAL 43 N',
                     'REM HFIX_VAL 13 CA CB',
                     'REM HFIX_VAL 33 CG1 CG2\n']}

elseALL = {'All': ['DFIX_* 1.329 C_- N',
                   'DANG_* 2.425 CA_- N',
                   'DANG_* 2.250 O_- N',
                   'DANG_* 2.435 C_- CA',
                   'FLAT_* 2.0 O_- CA_- N C_- CA\n'],
           'Ala': ['CHIV_ALA C',
                   'CHIV_ALA 2.477 CA',
                   'DFIX_ALA 1.231 C O',
                   'DFIX_ALA 1.525 C CA',
                   'DFIX_ALA 1.521 CA CB',
                   'DFIX_ALA 1.458 N CA',
                   'DANG_ALA 2.462 C N',
                   'DANG_ALA 2.401 O CA',
                   'DANG_ALA 2.503 C CB',
                   'DANG_ALA 2.446 CB N\n'],
           'Arg': ['CHIV_ARG C CZ',
                   'CHIV_ARG 2.503 CA',
                   'FLAT_ARG 2.0 CD NH1 NH2 NE CZ',
                   'DFIX_ARG 1.231 C O',
                   'DFIX_ARG 1.458 CA N',
                   'DFIX_ARG 1.525 C CA',
                   'DFIX_ARG 1.530 CA CB',
                   'DFIX_ARG 1.520 CB CG CG CD',
                   'DFIX_ARG 1.460 CD NE',
                   'DFIX_ARG 1.326 CZ NE CZ NH1 CZ NH2',
                   'DANG_ARG 2.455 N CB',
                   'DANG_ARG 2.401 O CA',
                   'DANG_ARG 2.504 C CB',
                   'DANG_ARG 2.462 C N',
                   'DANG_ARG 2.559 CA CG',
                   'DANG_ARG 2.510 CB CD',
                   'DANG_ARG 2.471 CG NE',
                   'DANG_ARG 2.466 CD CZ',
                   'DANG_ARG 2.299 NE NH1 NE NH2',
                   'DANG_ARG 2.293 NH1 NH2\n'],
           'Asn': ['CHIV_ASN C CG',
                   'CHIV_ASN 2.503 CA',
                   'DFIX_ASN 1.231 C O CG OD1',
                   'DFIX_ASN 1.525 C CA',
                   'DFIX_ASN 1.458 N CA',
                   'DFIX_ASN 1.530 CA CB',
                   'DFIX_ASN 1.516 CB CG',
                   'DFIX_ASN 1.328 CG ND2',
                   'DANG_ASN 2.401 O CA',
                   'DANG_ASN 2.462 C N',
                   'DANG_ASN 2.455 CB N',
                   'DANG_ASN 2.504 C CB',
                   'DANG_ASN 2.534 CA CG',
                   'DANG_ASN 2.393 CB OD1',
                   'DANG_ASN 2.419 CB ND2',
                   'DANG_ASN 2.245 OD1 ND2\n'],
           'Asp': ['CHIV_ASP C CG',
                   'CHIV_ASP 2.503 CA',
                   'DFIX_ASP 1.231 C O',
                   'DFIX_ASP 1.525 C CA',
                   'DFIX_ASP 1.530 CA CB',
                   'DFIX_ASP 1.516 CB CG',
                   'DFIX_ASP 1.458 CA N',
                   'DFIX_ASP 1.249 CG OD1 CG OD2',
                   'DANG_ASP 2.401 O CA',
                   'DANG_ASP 2.462 C N',
                   'DANG_ASP 2.455 CB N',
                   'DANG_ASP 2.504 C CB',
                   'DANG_ASP 2.534 CA CG',
                   'DANG_ASP 2.379 CB OD1 CB OD2',
                   'DANG_ASP 2.194 OD1 OD2\n'],
           'Cys': ['CHIV_CYS C',
                   'CHIV_CYS 2.503 CA',
                   'DFIX_CYS 1.231 C O',
                   'DFIX_CYS 1.525 C CA',
                   'DFIX_CYS 1.458 N CA',
                   'DFIX_CYS 1.530 CA CB',
                   'DFIX_CYS 1.808 CB SG',
                   'DANG_CYS 2.401 O CA',
                   'DANG_CYS 2.504 C CB',
                   'DANG_CYS 2.455 CB N',
                   'DANG_CYS 2.462 C N',
                   'DANG_CYS 2.810 CA SG\n'],
           'Gln': ['CHIV_GLN C CD',
                   'CHIV_GLN 2.503 CA',
                   'DFIX_GLN 1.231 C O',
                   'DFIX_GLN 1.458 N CA',
                   'DFIX_GLN 1.525 C CA',
                   'DFIX_GLN 1.530 CA CB',
                   'DFIX_GLN 1.520 CB CG',
                   'DFIX_GLN 1.516 CG CD',
                   'DFIX_GLN 1.231 CD OE1',
                   'DFIX_GLN 1.328 CD NE2',
                   'DANG_GLN 2.401 O CA',
                   'DANG_GLN 2.462 C N',
                   'DANG_GLN 2.455 CB N',
                   'DANG_GLN 2.504 C CB',
                   'DANG_GLN 2.559 CA CG',
                   'DANG_GLN 2.526 CB CD',
                   'DANG_GLN 2.393 CG OE1',
                   'DANG_GLN 2.419 CG NE2',
                   'DANG_GLN 2.245 OE1 NE2\n'],
           'Glu': ['CHIV_GLU C CD',
                   'CHIV_GLU 2.503 CA',
                   'DFIX_GLU 1.231 C O',
                   'DFIX_GLU 1.458 N CA',
                   'DFIX_GLU 1.525 C CA',
                   'DFIX_GLU 1.530 CA CB',
                   'DFIX_GLU 1.520 CB CG',
                   'DFIX_GLU 1.516 CG CD',
                   'DFIX_GLU 1.249 CD OE1 CD OE2',
                   'DANG_GLU 2.401 O CA',
                   'DANG_GLU 2.462 C N',
                   'DANG_GLU 2.455 CB N',
                   'DANG_GLU 2.504 C CB',
                   'DANG_GLU 2.559 CA CG',
                   'DANG_GLU 2.526 CB CD',
                   'DANG_GLU 2.379 CG OE1 CG OE2',
                   'DANG_GLU 2.194 OE1 OE2\n'],
           'Gly': ['CHIV_GLY C',
                   'DFIX_GLY 1.231 O C',
                   'DFIX_GLY 1.516 C CA',
                   'DFIX_GLY 1.451 CA N',
                   'DANG_GLY 2.467 C N',
                   'DANG_GLY 2.393 O CA\n'],
           'His': ['FLAT_HIS CB ND1 NE2 CD2 CE1 CG',
                   'CHIV_HIS C',
                   'CHIV_HIS 2.503 CA',
                   'DFIX_HIS 1.231 C O',
                   'DFIX_HIS 1.525 C CA',
                   'DFIX_HIS 1.458 CA N',
                   'DFIX_HIS 1.530 CA CB',
                   'DFIX_HIS 1.497 CB CG',
                   'DFIX_HIS 1.378 CG ND1',
                   'DFIX_HIS 1.321 ND1 CE1 CE1 NE2',
                   'DFIX_HIS 1.374 NE2 CD2',
                   'DFIX_HIS 1.354 CD2 CG',
                   'DANG_HIS 2.401 O CA',
                   'DANG_HIS 2.462 C N',
                   'DANG_HIS 2.504 C CB',
                   'DANG_HIS 2.455 N CB',
                   'DANG_HIS 2.536 CA CG',
                   'DANG_HIS 2.524 CB ND1',
                   'DANG_HIS 2.597 CB CD2',
                   'DANG_HIS 2.202 CG CE1',
                   'DANG_HIS 2.196 CG NE2',
                   'DANG_HIS 2.194 CE1 CD2',
                   'DANG_HIS 2.143 ND1 NE2',
                   'DANG_HIS 2.170 ND1 CD2\n'],
           'Ile': ['CHIV_ILE C',
                   'CHIV_ILE 2.516 CA',
                   'CHIV_ILE 2.495 CB',
                   'DFIX_ILE 1.231 C O',
                   'DFIX_ILE 1.525 C CA',
                   'DFIX_ILE 1.458 CA N',
                   'DFIX_ILE 1.540 CA CB',
                   'DFIX_ILE 1.530 CB CG1',
                   'DFIX_ILE 1.521 CB CG2',
                   'DFIX_ILE 1.513 CG1 CD1',
                   'DANG_ILE 2.401 O CA',
                   'DANG_ILE 2.462 C N',
                   'DANG_ILE 2.479 N CB',
                   'DANG_ILE 2.576 CA CG1',
                   'DANG_ILE 2.515 CA CG2',
                   'DANG_ILE 2.549 CB CD1',
                   'DANG_ILE 2.510 CG1 CG2',
                   'DANG_ILE 2.497 C CB\n'],
           'Leu': ['CHIV_LEU C',
                   'CHIV_LEU 2.503 CA',
                   'CHIV_LEU -2.589 CG',
                   'DFIX_LEU 1.231 C O',
                   'DFIX_LEU 1.525 C CA',
                   'DFIX_LEU 1.458 N CA',
                   'DFIX_LEU 1.530 CA CB CB CG',
                   'DFIX_LEU 1.521 CG CD1 CG CD2',
                   'DANG_LEU 2.401 O CA',
                   'DANG_LEU 2.462 C N',
                   'DANG_LEU 2.455 N CB',
                   'DANG_LEU 2.504 C CB',
                   'DANG_LEU 2.599 CA CG',
                   'DANG_LEU 2.510 CB CD1 CB CD2',
                   'DANG_LEU 2.504 CD1 CD2\n'],
           'Lys': ['CHIV_LYS C',
                   'CHIV_LYS 2.503 CA',
                   'DFIX_LYS 1.231 C O',
                   'DFIX_LYS 1.525 C CA',
                   'DFIX_LYS 1.458 CA N',
                   'DFIX_LYS 1.530 CA CB',
                   'DFIX_LYS 1.520 CB CG CG CD CD CE',
                   'DFIX_LYS 1.489 CE NZ',
                   'DANG_LYS 2.401 O CA',
                   'DANG_LYS 2.462 C N',
                   'DANG_LYS 2.455 N CB',
                   'DANG_LYS 2.504 C CB',
                   'DANG_LYS 2.559 CA CG',
                   'DANG_LYS 2.510 CB CD CG CE',
                   'DANG_LYS 2.493 CD NZ\n'],
           'Met': ['CHIV_MET C',
                   'CHIV_MET 2.503 CA',
                   'DFIX_MET 1.231 C O',
                   'DFIX_MET 1.458 N CA',
                   'DFIX_MET 1.525 C CA',
                   'DFIX_MET 1.530 CA CB',
                   'DFIX_MET 1.520 CB CG',
                   'DFIX_MET 1.803 CG SD',
                   'DFIX_MET 1.791 SD CE',
                   'DANG_MET 2.401 O CA',
                   'DANG_MET 2.462 C N',
                   'DANG_MET 2.455 N CB',
                   'DANG_MET 2.559 CA CG',
                   'DANG_MET 2.771 CB SD',
                   'DANG_MET 2.504 C CB',
                   'DANG_MET 2.771 CG CE\n'],
           'Phe': ['FLAT_PHE CG CD1 CE2 CB CD2 CE1 CZ',
                   'CHIV_PHE C',
                   'CHIV_PHE 2.503 CA',
                   'DFIX_PHE 1.231 C O',
                   'DFIX_PHE 1.458 N CA',
                   'DFIX_PHE 1.525 C CA',
                   'DFIX_PHE 1.530 CA CB',
                   'DFIX_PHE 1.502 CB CG',
                   'DFIX_PHE 1.384 CG CD1 CG CD2',
                   'DFIX_PHE 1.382 CD1 CE1 CD2 CE2 CE1 CZ CE2 CZ',
                   'DANG_PHE 2.401 O CA',
                   'DANG_PHE 2.462 C N',
                   'DANG_PHE 2.504 C CB',
                   'DANG_PHE 2.455 N CB',
                   'DANG_PHE 2.555 CA CG',
                   'DANG_PHE 2.525 CB CD1 CB CD2',
                   'DANG_PHE 2.404 CG CE1 CG CE2',
                   'DANG_PHE 2.394 CD1 CZ CD2 CZ CE1 CE2',
                   'DANG_PHE 2.380 CD1 CD2\n'],
           'Pro': ['CHIV_PRO C N',
                   'CHIV_PRO 2.728 CA',
                   'DFIX_PRO 1.231 C O',
                   'DFIX_PRO 1.525 C CA',
                   'DFIX_PRO 1.466 CA N',
                   'DFIX_PRO 1.473 N CD',
                   'DFIX_PRO 1.503 CD CG',
                   'DFIX_PRO 1.492 CG CB',
                   'DFIX_PRO 1.530 CB CA',
                   'DANG_PRO 2.401 O CA',
                   'DANG_PRO 2.477 C N',
                   'DANG_PRO 2.504 C CB',
                   'DANG_PRO 2.437 CA CD',
                   'DANG_PRO 2.332 N CG',
                   'DANG_PRO 2.393 CD CB',
                   'DANG_PRO 2.390 CA CG',
                   'DANG_PRO 2.345 N CB',
                   'DANG_PRO 2.497 CD C_-\n'],
           'Ser': ['CHIV_SER C',
                   'CHIV_SER 2.503 CA',
                   'DFIX_SER 1.231 C O',
                   'DFIX_SER 1.525 C CA',
                   'DFIX_SER 1.458 N CA',
                   'DFIX_SER 1.530 CA CB',
                   'DFIX_SER 1.417 CB OG',
                   'DANG_SER 2.401 O CA',
                   'DANG_SER 2.462 C N',
                   'DANG_SER 2.504 C CB',
                   'DANG_SER 2.455 N CB',
                   'DANG_SER 2.431 CA OG\n'],
           'Thr': ['CHIV_THR C',
                   'CHIV_THR 2.516 CA',
                   'CHIV_THR -2.628 CB',
                   'DFIX_THR 1.231 C O',
                   'DFIX_THR 1.525 C CA',
                   'DFIX_THR 1.458 N CA',
                   'DFIX_THR 1.540 CA CB',
                   'DFIX_THR 1.433 CB OG1',
                   'DFIX_THR 1.521 CB CG2',
                   'DANG_THR 2.401 O CA',
                   'DANG_THR 2.462 C N',
                   'DANG_THR 2.497 C CB',
                   'DANG_THR 2.479 N CB',
                   'DANG_THR 2.430 CA OG1',
                   'DANG_THR 2.515 CA CG2',
                   'DANG_THR 2.373 OG1 CG2\n'],
           'Trp': ['FLAT_TRP CB CE2 CZ3 CG CD1 NE1 CD2 CZ2 CH2 CE3',
                   'CHIV_TRP C',
                   'CHIV_TRP 2.503 CA',
                   'DFIX_TRP 1.231 C O',
                   'DFIX_TRP 1.525 C CA',
                   'DFIX_TRP 1.458 N CA',
                   'DFIX_TRP 1.530 CA CB',
                   'DFIX_TRP 1.498 CB CG',
                   'DFIX_TRP 1.365 CG CD1',
                   'DFIX_TRP 1.374 CD1 NE1',
                   'DFIX_TRP 1.370 NE1 CE2',
                   'DFIX_TRP 1.394 CE2 CZ2',
                   'DFIX_TRP 1.368 CZ2 CH2',
                   'DFIX_TRP 1.400 CH2 CZ3',
                   'DFIX_TRP 1.382 CZ3 CE3',
                   'DFIX_TRP 1.398 CE3 CD2',
                   'DFIX_TRP 1.433 CD2 CG',
                   'DFIX_TRP 1.409 CD2 CE2',
                   'DANG_TRP 2.401 O CA',
                   'DANG_TRP 2.462 C N',
                   'DANG_TRP 2.504 C CB',
                   'DANG_TRP 2.455 N CB',
                   'DANG_TRP 2.534 CA CG',
                   'DANG_TRP 2.562 CB CD1',
                   'DANG_TRP 2.621 CB CD2',
                   'DANG_TRP 2.246 CG NE1',
                   'DANG_TRP 2.605 CG CE3',
                   'DANG_TRP 2.288 CG CE2',
                   'DANG_TRP 2.233 CD1 CE2',
                   'DANG_TRP 2.239 CD1 CD2',
                   'DANG_TRP 2.240 NE1 CD2',
                   'DANG_TRP 2.361 CE2 CH2',
                   'DANG_TRP 2.416 CE2 CE3',
                   'DANG_TRP 2.390 CD2 CZ3',
                   'DANG_TRP 2.456 CD2 CZ2',
                   'DANG_TRP 2.423 CE3 CH2',
                   'DANG_TRP 2.415 CZ3 CZ2',
                   'DANG_TRP 2.506 NE1 CZ2\n'],
           'Tyr': ['FLAT_TYR CB CD1 CE2 CG CD2 CE1 CZ OH',
                   'CHIV_TYR C',
                   'CHIV_TYR 2.503 CA',
                   'DFIX_TYR 1.231 C O',
                   'DFIX_TYR 1.458 N CA',
                   'DFIX_TYR 1.525 C CA',
                   'DFIX_TYR 1.530 CA CB',
                   'DFIX_TYR 1.512 CB CG',
                   'DFIX_TYR 1.389 CG CD2 CG CD1',
                   'DFIX_TYR 1.382 CD2 CE2 CD1 CE1',
                   'DFIX_TYR 1.378 CE2 CZ CE1 CZ',
                   'DFIX_TYR 1.376 CZ OH',
                   'DANG_TYR 2.401 O CA',
                   'DANG_TYR 2.462 C N',
                   'DANG_TYR 2.455 N CB',
                   'DANG_TYR 2.504 C CB',
                   'DANG_TYR 2.550 CA CG',
                   'DANG_TYR 2.523 CB CD1 CB CD2',
                   'DANG_TYR 2.414 CG CE1 CG CE2',
                   'DANG_TYR 2.385 CZ CD1 CZ CD2',
                   'DANG_TYR 2.384 OH CE1 OH CE2',
                   'DANG_TYR 2.382 CD1 CD2',
                   'DANG_TYR 2.390 CE1 CE2\n'],
           'Val': ['CHIV_VAL C',
                   'CHIV_VAL 2.516 CA',
                   'CHIV_VAL -2.622 CB',
                   'DFIX_VAL 1.231 C O',
                   'DFIX_VAL 1.458 N CA',
                   'DFIX_VAL 1.525 C CA',
                   'DFIX_VAL 1.540 CA CB',
                   'DFIX_VAL 1.521 CB CG2 CB CG1',
                   'DANG_VAL 2.401 O CA',
                   'DANG_VAL 2.462 C N',
                   'DANG_VAL 2.497 C CB',
                   'DANG_VAL 2.515 CA CG1 CA CG2',
                   'DANG_VAL 2.479 N CB',
                   'DANG_VAL 2.504 CG1 CG2\n']}

instructions = [rtabAll, hfixAll, elseALL]









